import { IListOfLeave } from '../interfaces'

export const dummyData: IListOfLeave[] = [
  {
    id: 1,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'I want to absent because Im Kalibangon'
  },
  {
    id: 2,
    name: 'Joshua Galit',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What do you like most that I do in bed?'
  },
  {
    id: 3,
    name: 'James Niel',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What’s your favorite time of day to be intimate?'
  },
  {
    id: 4,
    name: 'Mc Arthor',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What was your favorite toy growing up?'
  },
  {
    id: 5,
    name: 'Rapsody',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: false,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'I want to absent because Im Kalibangon'
  },
  {
    id: 6,
    name: 'James Gouse',
    project: 'Hello Team',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'When did you know you wanted to be monogamous with me?'
  },
  {
    id: 7,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/31/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'Do you ever get jealous if you see me talking to other attractive people?'
  },
  {
    id: 8,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Deadly Basication',
    isWithPay: false,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'Who do you most like to poke fun at?'
  },
  {
    id: 9,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What do you think we need to work on the most in our relationship?'
  },
  {
    id: 10,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'If you got sick, do you think I would be there to care for you?'
  },
  {
    id: 11,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'Do you believe that I love you?'
  },
  {
    id: 12,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'When did you know you wanted to kiss me?'
  },
  {
    id: 13,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: false,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What’s your favorite activity that we do together?'
  },
  {
    id: 14,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Joshau Galit',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What talent would you want to possess if you could?'
  },
  {
    id: 15,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'James Dou',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What is your favorite thing I ever did for a special occasion for you?'
  },
  {
    id: 16,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What is your favorite fantasy?'
  },
  {
    id: 17,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'I want to absent because Im Kalibangon'
  },
  {
    id: 18,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'What is your favorite position?'
  },
  {
    id: 19,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'Do you ever think about me during the day?'
  },
  {
    id: 20,
    name: 'James Gouse',
    project: 'Team 6 Digit',
    leaveDate: '11/29/2023',
    type: 'Vacation Leave',
    isWithPay: true,
    manager: 'Madelyn Donin',
    projectLeader: 'Anika Bator',
    totalUndertime: 0,
    totalLeaves: 3,
    dateFiled: '11/20/2022',
    reason: 'Lights on or lights off?'
  }
]
