import { Clock, FileText, Home, Layers, Sunrise, Users } from 'react-feather'

import MyOvertimeIcon from './../icons/MyOvertimeIcon'
import { IDTRManagement, ISidebarLink } from './../interfaces'

export const sidebarLinks = {
  my_nav: [
    {
      name: 'Home',
      Icon: Home,
      href: '/'
    },
    {
      name: 'My Leaves',
      Icon: FileText,
      href: '/my-leaves'
    },
    {
      name: 'My Daily Time Record',
      Icon: Clock,
      href: '/my-daily-time-record'
    },
    {
      name: 'My Overtime',
      href: '/my-overtime',
      Icon: MyOvertimeIcon
    }
  ] as ISidebarLink[],
  management: [
    {
      name: 'Schedule Management',
      Icon: Sunrise,
      href: '/schedule-management'
    },
    {
      name: 'Employee Management',
      Icon: Users,
      href: '/employee-management'
    },
    {
      name: 'Leave Management',
      Icon: FileText,
      href: '/leave-management'
    },
    {
      name: 'DTR Management',
      Icon: Clock,
      href: '/dtr-management'
    },
    {
      name: 'Overtime Management',
      Icon: Layers,
      href: '/overtime-management'
    }
  ] as ISidebarLink[]
}
export const dtrManagementData: IDTRManagement[] = [
  {
    id: 1,
    name: 'joshua galit',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'Sick Leave'
  },
  {
    id: 2,
    name: 'aspen vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'Vacation Leave'
  },
  {
    id: 3,
    name: 'ruben culhane',
    time_in: '10:00',
    time_out: '18:30',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 120,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 4,
    name: 'carla kenter',
    time_in: '09:30',
    time_out: '18:30',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'Sick Leave'
  },
  {
    id: 5,
    name: 'Paityn Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 6,
    name: 'Aspen Siphron',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 7,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 8,
    name: 'Allison Curtis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 9,
    name: 'Rayna Bergson',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 10,
    name: 'Terry Schleifer',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'Absent'
  },
  {
    id: 10,
    name: 'Zaire Passaquindici Arcand',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 11,
    name: 'Phillip Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 12,
    name: 'Makenna Vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 13,
    name: 'Jaydon Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'Absent'
  },
  {
    id: 14,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 15,
    name: 'Paityn Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 16,
    name: 'Zaire Passaquindici Arcand',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 17,
    name: 'Phillip Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 18,
    name: 'Makenna Vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 19,
    name: 'Jaydon Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 20,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 21,
    name: 'Paityn Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 22,
    name: 'Zaire Passaquindici Arcand',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 23,
    name: 'Phillip Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 24,
    name: 'Makenna Vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 25,
    name: 'Jaydon Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 26,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 27,
    name: 'Paityn Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 28,
    name: 'Zaire Passaquindici Arcand',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 29,
    name: 'Phillip Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 31,
    name: 'Makenna Vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 32,
    name: 'Jaydon Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 33,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 34,
    name: 'Paityn Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 35,
    name: 'Zaire Passaquindici Arcand',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 36,
    name: 'Phillip Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 37,
    name: 'Makenna Vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    work_hours: 0,
    start_time: '09:30',
    end_time: '06:30',
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 38,
    name: 'Jaydon Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 39,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 40,
    name: 'Paityn Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 41,
    name: 'Zaire Passaquindici Arcand',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 42,
    name: 'Phillip Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'Absent'
  },
  {
    id: 43,
    name: 'Makenna Vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 44,
    name: 'Jaydon Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '10:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 44,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 45,
    name: 'Paityn Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'Absent'
  },
  {
    id: 46,
    name: 'Zaire Passaquindici Arcand',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 47,
    name: 'Phillip Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 48,
    name: 'Makenna Vetrovs',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 49,
    name: 'Jaydon Dokidis',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 50,
    name: 'Ryan Korsgaard',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  },
  {
    id: 51,
    name: 'Paityn Geidt',
    time_in: '00:00',
    time_out: '00:00',
    start_time: '09:30',
    end_time: '06:30',
    work_hours: 0,
    late: 0,
    undertime: 0,
    overtime: 0,
    status: 'On-Duty'
  }
]
